### ISSUE TITLE
Please support url link for image and support iframe.

### ISSUE THREAD

**Issue by korenevskiy** [jquery-ui-rails/jquery-ui-rails#119]
Please support functions as "SqueezeBox". 
1. Open modal windows with image from url "< a href='img/image.jpg'>modal image< / a>"
2. Open modal windows with site in <iframe/> from url "< a href='domain.com/' >modal site in iframe< / a >"
.
Example: https://www.spiralscripts.co.uk/Joomla-Tips/using-modal-windows-with-joomla.html

**Comment by skateinmars** [comment]
jquery-ui-rails is only the gem that helps integrate jquery-ui into rails.
Please redirect your feature requests to the jquery-ui team :)
