### ISSUE TITLE
Failed to load resource: ui-icons_222222_256x240.png

### ISSUE THREAD

**Issue by stereosupersonic** [jquery-ui-rails/jquery-ui-rails#127]
We use the datepicker in version 6.0.1. When this component is shown I get the error: ```ui-icons_222222_256x240.png Failed to load resource: the server responded with a status of 404 (Not Found)```.
This file was removed here https://github.com/jquery-ui-rails/jquery-ui-rails/commit/d504a40538fe5f7998439ad2f8fc5c4a1f843f1c#diff-ab769107a6359f8708f91b3d1dc33559

Could this file be added

**Comment by Borzik** [comment]
This file is no longer part of jQuery UI, and there are no references to it anywhere in `jquery-ui-rails` code.
Please compare [jQuery UI's images folder](https://github.com/jquery/jquery-ui/tree/master/themes/base/images) and [jquery-ui-rails images folder](https://github.com/jquery-ui-rails/jquery-ui-rails/tree/master/app/assets/images/jquery-ui). This gem only converts what is provided by jQuery UI to Rails-friendly format.
Maybe this file is referenced in your local stylesheets for some reason?
